name : 03 - Workflow Runners
on: 
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This job is running on $RUNNER_OS"
      - name: Displaying Github context
        run: echo "${{toJson(github)}}"
  windows-echo:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Show OS
        run: echo "This job is running on $RUNNER_OS"
      - name: Displaying Github context
        run: echo "${{toJson(github)}}"
  macos-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: echo "This job is running on $RUNNER_OS"
      - name: Displaying Github context
        run: echo "${{toJson(github)}}"
