name: 04 - Using Actions
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking working directory
        working-directory: 04-using-actions/react-app
        run: ls -la
      - name: Printing Folders Before Checkout
        run: ls -la
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Printing files before Install
        run: |
          cd 04-using-actions/react-app
          ls -la
      - name: Install Dependencies
        run: npm ci    
      - name: checking working directory path
        run: pwd
      - name: Printing Folders After Checkout
        run: ls -la
      