name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{inputs.debug == true && 'ON'||'OFF'}}
on:
  push:

  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: true
      
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{inputs.debug == true}}
        run: |
          echo "Triggered by: ${{github.actor}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"
        

      - name: "[debug] Print start-up data - with expresion in if"
        if: inputs.debug == true
        run: |
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"

      - name: "[debug] Print when triggered from main"
        if:  inputs.debug == false &&  github.ref == 'refs/heads/main'
        run: |
          echo "${{ inputs.debug }}"
          echo "${{ github.ref }}"
          echo "This run was triggered from the main branch."

      - name: Greet User
        run: echo "Hello, world!"
