name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18.x
          - 19.x
          - 20.x
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            tag: experimental
          - node_version: 18.x
            tag: experimental
        fail-fast: 
          - false
    name: Node ${{ matrix.os}} - ${{ matrix.node_version }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimentals' }}
        run: exit 1
      - name: Perform some tests
        run: |
          sleep 10
      - name: Upload test results
        run: echo "Uploading test resultsSSS"