name : 16 - Working with Environments
on: 
  workflow_dispatch:
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploying to staging
        run: echo "Env variable  ${{vars.MY_ENV_VALUE || 'default value'}}" 

  e2e-tests:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: E2E tests
        run : echo "Running E2E"
  deploy-prod:
    needs: e2e-tests
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo vars
        run: |
          echo "Deploying to prod"
          echo " Env variable: ${{vars.MY_ENV_VALUE || 'default value'}}"
  deploy-prod1:
    needs: e2e-tests
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo vars
        run: |
          echo "Deploying to prod"
          echo " Env variable: ${{vars.MY_ENV_VALUE || 'default value'}}"

  deploy-prod2:
    needs: e2e-tests
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo vars
        run: |
          echo "Deploying to prod"
          echo " Env variable: ${{vars.MY_ENV_VALUE || 'default value'}}"




      
        
        
      

