name: 17 - 1 - Custom Actions - Composite
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: 'Select the environment to deploy'
        options:
          - dev
          - prod
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        id: setup-deps
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: '18.x'
          working-dir: ${{env.working-directory}}
          target-env: ${{inputs.target-env}}
      - name: Print Setup Depencies output
        run: |
          echo "Installed Deps: ${{steps.setup-deps.outputs.installed-deps}}"
          echo "Below Json Data is output of steps context"
          echo "${{toJson(steps)}}"
      - name: test
        run: npm run test
      - name: build
        run: npm run build
