name: 18 - 2 - Reusable Workflows
on: 
  workflow_dispatch:
jobs:
  deploys:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: test-directory
  print-outputs:
    needs: deploys
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: |
          echo "${{toJson(needs)}}"
          echo "Build status: ${{needs.deploys.outputs.build-status}}"
          echo "url: ${{needs.deploys.outputs.url}}"