name: ADF CI/CD with Key Vault
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

        - name: setup NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: node package manager install
          run: npm install
          working-directory: ${{github.workspace}}/build
        
        - name: validate ADF
          run: npm run build validate  ${{github.workspace}}  /subscriptions/ee998db0-384c-47f0-8674-11be01fea10d/resourceGroups/g_dev_shankar_cicd/providers/Microsoft.DataFactory/factories/adf-dev-shankar-cicd

        - name: genrate ARM Template
          run: npm run build export ${{github.workspace}}  /subscriptions/ee998db0-384c-47f0-8674-11be01fea10d/resourceGroups/g_dev_shankar_cicd/providers/Microsoft.DataFactory/factories/adf-dev-shankar-cicd 'ExportedArmTemplate'
          working-directory: ${{github.workspace}}/build

        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ExportedArmTemplate
            path: ${{github.workspace}}/build/ExportedArmTemplate
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download ARM Templates
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: true
      - name: Deploy ARM Template
        uses: AzureAzure/arm-deploy@v2